
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
           python-version: "3.14"

      - name: Sync dependencies
        run: uv sync --group dev

      - name: Run lint
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.14"
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Download uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group dev

      - name: Test package
        run: uv run pytest

  pass:
    name: Required checks
    if: always()
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
